sudo: required 
services: 
  - docker 

before_install: 
  # Get encrypted json 
  openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d

  # Download Google Cloud SDK & install locally. 
  - curl https://sdk.cloud.google.com | bash > /dev/null; 

  # Apply config info. 
  - source $HOME/google-cloud-sdk/path.bash.inc 

  # Install kubectl 
  - gcloud components update kubectl 

  # Authorize with GCloud. Credentials are stored in service-account.json  
  - gcloud auth activate-service-account --key-file service-account.json 


